# Generated by Django 3.2.9 on 2021-12-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name_plural': 'Author Status'},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='designation',
            new_name='author_status',
        ),
        migrations.RemoveField(
            model_name='author',
            name='status',
        ),
    ]
