# Generated by Django 3.2.9 on 2021-12-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211208_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
