# Generated by Django 3.2.9 on 2021-12-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gallery_1',
            field=models.ImageField(blank=True, null=True, upload_to='blog/post/feature_img/'),
        ),
        migrations.AddField(
            model_name='post',
            name='gallery_2',
            field=models.ImageField(blank=True, null=True, upload_to='blog/post/feature_img/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/post/feature_img/'),
        ),
    ]
