# Generated by Django 3.2.9 on 2021-12-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211221_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='visit_count',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='blog/post/feature_img/'),
            preserve_default=False,
        ),
    ]
