# Generated by Django 3.2.9 on 2021-12-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211221_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.AlterField(
            model_name='author',
            name='author_status',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('moderator', 'Moderator')], default='editor', max_length=10),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
