# Generated by Django 3.2.9 on 2021-12-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fast_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='img',
            new_name='image',
        ),
    ]
