# Generated by Django 3.2.9 on 2021-12-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='pinterest',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='contact_us',
            old_name='twiteer',
            new_name='twitter',
        ),
    ]
