# Generated by Django 3.2.9 on 2021-12-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_locationdetails_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
