# Generated by Django 3.2.9 on 2021-12-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='discount_percent',
        ),
        migrations.AddField(
            model_name='slider',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
