# Generated by Django 3.2.9 on 2021-12-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211206_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='locationdetails',
            options={'verbose_name_plural': 'Location Details'},
        ),
    ]
