# Generated by Django 3.2.9 on 2021-12-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_gang_talk_speacial_menu_tab_special_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='special_itme/'),
        ),
    ]
