# Generated by Django 3.2.9 on 2021-12-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_special_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special_item',
            name='assign_tab',
        ),
        migrations.DeleteModel(
            name='Speacial_menu_tab',
        ),
        migrations.DeleteModel(
            name='Special_item',
        ),
    ]
