# Generated by Django 3.2.9 on 2021-12-15 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0037_custom_order'),
        ('home', '0011_auto_20211215_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.category')),
                ('meal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.meal_category')),
            ],
        ),
    ]
