# Generated by Django 3.2.9 on 2021-12-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='discount_percent',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
