# Generated by Django 3.2.9 on 2021-12-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_slider_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationdetails',
            old_name='title',
            new_name='name',
        ),
    ]
