# Generated by Django 3.2.9 on 2021-12-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20211220_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_info',
            old_name='phone2',
            new_name='fax',
        ),
    ]
