# Generated by Django 3.2.9 on 2021-12-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0043_delete_menu'),
        ('home', '0017_rename_phone2_company_info_fax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='menu_package',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu_package'),
            preserve_default=False,
        ),
    ]
