# Generated by Django 3.2.9 on 2021-12-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_feature_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='meal_time/')),
            ],
        ),
    ]
