# Generated by Django 3.2.9 on 2021-12-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_meal_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company_info',
            options={'verbose_name_plural': 'Company Information'},
        ),
        migrations.RenameField(
            model_name='company_info',
            old_name='about_contact',
            new_name='about',
        ),
    ]
