# Generated by Django 3.2.9 on 2021-12-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20211220_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='LocationDetails',
        ),
    ]
