# Generated by Django 3.2.9 on 2021-12-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20211221_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop',
            new_name='shop_title',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
    ]
