# Generated by Django 3.2.9 on 2021-12-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20211221_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gang_talk',
            options={'verbose_name_plural': 'Gang Talks Home Content'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'History'},
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='author_sign',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
