# Generated by Django 3.2.9 on 2021-12-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20211208_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.offer'),
            preserve_default=False,
        ),
    ]
