# Generated by Django 3.2.9 on 2021-12-09 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20211208_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tab',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.offer'),
        ),
    ]
