# Generated by Django 3.2.9 on 2021-12-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_product_tab_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_tab',
            name='offer',
        ),
        migrations.AddField(
            model_name='product_tab',
            name='offer',
            field=models.ManyToManyField(to='restaurant.Offer'),
        ),
    ]
