# Generated by Django 3.2.9 on 2021-12-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_menu_menu_item_menu_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_package',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_package',
            field=models.ManyToManyField(to='restaurant.Menu_package'),
        ),
    ]
