# Generated by Django 3.2.9 on 2021-12-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_auto_20211212_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.ManyToManyField(blank=True, to='restaurant.Offer'),
        ),
    ]
