# Generated by Django 3.2.9 on 2021-12-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_tab',
        ),
    ]
