# Generated by Django 3.2.9 on 2021-12-12 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_remove_product_product_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_tab_for',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product_tab',
            name='offer',
            field=models.ManyToManyField(blank=True, to='restaurant.Offer'),
        ),
        migrations.AddField(
            model_name='product_tab',
            name='prod_tab_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.product_tab_for'),
        ),
    ]
