# Generated by Django 3.2.9 on 2021-12-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_auto_20211212_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.product_tab'),
        ),
    ]
