# Generated by Django 3.2.9 on 2021-12-12 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_product_product_tab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_tab',
            old_name='prod_tab',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product_tab',
            name='offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='product_tab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.product_tab'),
        ),
    ]
