# Generated by Django 3.2.9 on 2021-12-12 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_auto_20211212_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product_tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab', to='restaurant.product_tab'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.ManyToManyField(blank=True, related_name='offer', to='restaurant.Offer'),
        ),
    ]
