# Generated by Django 3.2.9 on 2021-12-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_auto_20211212_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_for',
            new_name='name',
        ),
    ]
