# Generated by Django 3.2.9 on 2021-12-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_rename_menu_for_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.AddField(
            model_name='menu_package',
            name='price',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
