# Generated by Django 3.2.9 on 2021-12-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_auto_20211213_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_package',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='menu_item',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu_package'),
        ),
    ]
