# Generated by Django 3.2.9 on 2021-12-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_auto_20211213_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_package',
        ),
        migrations.AddField(
            model_name='menu_package',
            name='assign_menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu'),
        ),
    ]
