# Generated by Django 3.2.9 on 2021-12-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_auto_20211213_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='package',
        ),
        migrations.RemoveField(
            model_name='menu_package',
            name='assign_menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_package',
            field=models.ManyToManyField(to='restaurant.Menu_package'),
        ),
        migrations.AddField(
            model_name='menu_package',
            name='menu_item',
            field=models.ManyToManyField(to='restaurant.Menu_item'),
        ),
        migrations.AlterField(
            model_name='menu_package',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
