# Generated by Django 3.2.9 on 2021-12-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_auto_20211213_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_category',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Menu_item',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='menu_package',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='menu_package',
            name='item',
            field=models.ManyToManyField(to='restaurant.Item'),
        ),
    ]
