# Generated by Django 3.2.9 on 2021-12-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_auto_20211214_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_package',
            old_name='item',
            new_name='items',
        ),
    ]
