# Generated by Django 3.2.9 on 2021-12-14 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_rename_item_menu_package_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Catering_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='caterign/')),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('in_stock', models.BooleanField(default=True)),
                ('interested', models.BooleanField(default=False)),
                ('assign_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.catering_tab')),
                ('category', models.ManyToManyField(to='restaurant.Category')),
                ('items', models.ManyToManyField(to='restaurant.Item')),
            ],
        ),
    ]
