# Generated by Django 3.2.9 on 2021-12-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_catering_product_catering_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering_product',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
