# Generated by Django 3.2.9 on 2021-12-14 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_alter_catering_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='catering_product',
            name='product_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.product_for'),
            preserve_default=False,
        ),
    ]
