# Generated by Django 3.2.9 on 2021-12-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_catering_product_product_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='catering_product',
            name='description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
    ]
