# Generated by Django 3.2.9 on 2021-12-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0028_catering_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='catering_product',
            name='sku',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
