# Generated by Django 3.2.9 on 2021-12-14 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_catering_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_for',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_tab',
        ),
        migrations.RemoveField(
            model_name='product_tab',
            name='prod_tab_for',
        ),
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='restaurant.offer'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product_tab_for',
        ),
    ]
