# Generated by Django 3.2.9 on 2021-12-15 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_auto_20211214_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product_tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.product_tab'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.offer'),
        ),
    ]
