# Generated by Django 3.2.9 on 2021-12-15 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0031_auto_20211215_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_for',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.product_for'),
            preserve_default=False,
        ),
    ]
