# Generated by Django 3.2.9 on 2021-12-15 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0034_auto_20211215_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.meal_category'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_package',
            field=models.ManyToManyField(blank=True, to='restaurant.Menu_package'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu_package',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
