# Generated by Django 3.2.9 on 2021-12-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0035_auto_20211215_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custom_order',
        ),
    ]
