# Generated by Django 3.2.9 on 2021-12-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0038_custom_order_is_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catering_product',
            name='product_for',
        ),
        migrations.RemoveField(
            model_name='catering_product',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_for',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Product_for',
        ),
    ]
