# Generated by Django 3.2.9 on 2021-12-20 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0039_auto_20211219_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_package',
            name='description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu_package',
            name='image',
            field=models.ImageField(default=1, upload_to='menu_package/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu_package',
            name='meal_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.meal_category'),
        ),
    ]
