# Generated by Django 3.2.9 on 2021-12-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0042_meal_category_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
