# Generated by Django 3.2.9 on 2021-12-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0043_delete_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catering_product',
            options={'verbose_name_plural': 'Catering Product'},
        ),
        migrations.AlterModelOptions(
            name='catering_tab',
            options={'verbose_name_plural': 'Catering Tab'},
        ),
        migrations.AlterModelOptions(
            name='custom_order',
            options={'verbose_name_plural': 'Custom Order'},
        ),
        migrations.AlterModelOptions(
            name='meal_category',
            options={'verbose_name_plural': 'Meal Category'},
        ),
        migrations.AlterModelOptions(
            name='menu_package',
            options={'verbose_name_plural': 'Menu Packages'},
        ),
        migrations.AlterModelOptions(
            name='product_tab',
            options={'verbose_name_plural': 'Product Tab'},
        ),
    ]
