# Generated by Django 3.2.9 on 2021-12-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0044_auto_20211220_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_stock',
            new_name='in_stock',
        ),
    ]
