# Generated by Django 3.2.9 on 2021-12-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0045_rename_is_stock_product_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='product',
            name='assign_tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.catering_tab'),
        ),
        migrations.AddField(
            model_name='product',
            name='items',
            field=models.ManyToManyField(blank=True, to='restaurant.Item'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.offer'),
        ),
    ]
