# Generated by Django 3.2.9 on 2021-12-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0046_auto_20211220_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='assign_tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.catering_tab', verbose_name='Assign Tab(For Catering Product)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='items',
            field=models.ManyToManyField(blank=True, to='restaurant.Item', verbose_name='Items(For Catering Product)'),
        ),
    ]
