# Generated by Django 3.2.9 on 2021-12-21 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0047_auto_20211221_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catering_product',
        ),
    ]
