# Generated by Django 3.2.9 on 2021-12-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20211222_1952'),
        ('restaurant', '0049_auto_20211221_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='items',
            field=models.ManyToManyField(blank=True, to='restaurant.Item', verbose_name='Items(For Catering & Menu Product)'),
        ),
        migrations.DeleteModel(
            name='Menu_package',
        ),
    ]
