# Generated by Django 3.2.9 on 2021-12-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0050_auto_20211222_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_response',
            field=models.BooleanField(default=False),
        ),
    ]
